### ISSUE TITLE
ReferenceError: facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by Flyingprinter** [ionicthemes/facebook-login-with-ionic-framework#1]
ReferenceError: facebookConnectPlugin is not defined
:(

**Comment by Hardik21** [comment]
Still this error not resolved.

**Comment by djabif** [comment]
Hello @Hardik21 , this repo is for Ionic v1, for Ionic 3 and 4 please go to https://github.com/ionicthemes/ionic-facebook-login
