### ISSUE TITLE
ionic emulate ios -lc

### ISSUE THREAD

**Issue by Flyingprinter** [ionicthemes/facebook-login-with-ionic-framework#3]
I cant do the Live paramter. Any advice? I need to debug it.

**Comment by djabif** [comment]
You can use the following guides to see how to debug on real devices:

Remote Debugging on Android with Chrome
https://developer.chrome.com/devtools/docs/remote-debugging

Remote Debugging on iOS with Safari
http://www.jasenlew.com/2014/07/28/web-inspect-an-ionic-app-on-your-iphone-ios-6/
