### ISSUE TITLE
Not able to login 

### ISSUE THREAD

**Issue by ajaysaini95700** [ionicthemes/facebook-login-with-ionic-framework#8]
i am facing a problem whenever i login with facebook. is showing "invalid key hash.the key hash +H9|4+vy***********\* does not match any stored key hash". how to fix it

**Comment by djabif** [comment]
Please check the "Generate your own Key Hash" section from the documentation https://ionicthemes.com/tutorials/about/native-facebook-login-with-ionic-framework
